name: stripe_native_example
description: Demonstrates how to use the stripe_native plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  stripe_native:
    path: ../

flutter:
  uses-material-design: true
